* =kissrecents= - A KISS replacement of built-in =recentf=
** Why

Because the Emacs built-in =recentf= frustrate me over 10 years. I never understand what it is doing.

** What

A simple and stupid recents list, without any incomprehensible behaviors, just like any other IDE or editor. (I've falled into self-doubt for years whenever thinking that I have to implement such feature for a text editor in 2024.)

*** Characteristics

- No fucking cache. (data is merely a plaintext saved in =~/.emacs.d/.kissrecents-data=)
- Never lost any items after exiting, even killing Emacs.
- Always synchronize recents list between multiple Emacs instances.
- Supported list: files / directories / projects (directories controlled by VC, ex: =git=)

** Installation

#+begin_src emacs-lisp
(require 'kissrecents)
(global-set-key (kbd "C-x C-r") 'kissrecents-files)
(global-set-key (kbd "C-x C-d") 'kissrecents-directories)
(global-set-key (kbd "C-x C-p") 'kissrecents-projects)
#+end_src

You may want to add =.kissrecents-data= into =.gitignore=:

#+begin_src shell
cd ~/.emacs.d && echo ".kissrecents-data" >> .gitignore
#+end_src

** License
GPLv3
